.TH reunitize 1 reunitize\-0.0.0
.SH NAME
reunitize \- !!SUMMARY!!.SH SYNOPSIS
.B reunitize !!USAGE!!
.SH DESCRIPTION
.B reunitize
!!DESCRIPTION!!.SH OPTIONS
.LP
.B --help
Print a brief usage message.
.SH EXAMPLES
.LP
.B reunitize 
.SH FILES
.SH SEE ALSO
.TP
.BR ruby(1)
.TP
.IR 
.SH BUGS
Probably.
.SH LICENSE
Copyright  Noah Birnel

.sp
MIT