.TH reunitize 1 reunitize\-0.0.0
.SH NAME
reunitize \- generate an Ipro lfp by reviewing images
.SH SYNOPSIS
.B reunitize PATH
.SH DESCRIPTION
.B reunitize
opens a directory or directories in
.BR feh(1)
and generates an Ipro lfp based on
the keystrokes it receives from the user.
.LP
Nothing is implemented yet.
.SH OPTIONS
.LP
.B --help
Print a brief usage message.
.SH EXAMPLES
.LP
.B reunitize 
.SH SEE ALSO
.TP
.BR ruby(1)
.TP
.BR feh(1)
.SH BUGS
Probably.
.SH LICENSE
Copyright  Noah Birnel
.sp
MIT License
